#!/usr/bin/env python3
"""
Test script for Confluence integration.
"""

import os
import sys
from pathlib import Path
import requests
from datetime import datetime

# Add src to path for imports
sys.path.append('src')

try:
    from src.utils import env
    from src.publish_to_confluence import publish
except ImportError:
    print("❌ Error: Could not import required modules")
    print("Make sure you're running from the project root directory")
    sys.exit(1)


def test_confluence_connection():
    """Test basic Confluence API connection."""
    print("🧪 Testing Confluence Connection...")
    print("=" * 40)
    
    base_url = env('CONFLUENCE_BASE')
    username = env('CONFLUENCE_USER')
    api_token = env('CONFLUENCE_API_TOKEN')
    
    print(f"Base URL: {base_url or 'Not set'}")
    print(f"Username: {username or 'Not set'}")
    print(f"API Token: {'Set' if api_token else 'Not set'}")
    
    if not all([base_url, username, api_token]):
        print("\n❌ Confluence not configured. Please run:")
        print("1. Create API token: https://id.atlassian.com/manage-profile/security/api-tokens")
        print("2. Add to .env file:")
        print("   CONFLUENCE_BASE=https://yourcompany.atlassian.net")
        print("   CONFLUENCE_USER=your-email@company.com")
        print("   CONFLUENCE_API_TOKEN=your_token")
        return False
    
    try:
        headers = {
            'Accept': 'application/json',
            'Content-Type': 'application/json'
        }
        
        auth = (username, api_token)
        test_url = f"{base_url}/rest/api/space"
        
        print(f"\n🔍 Testing connection to: {test_url}")
        response = requests.get(test_url, headers=headers, auth=auth, timeout=10)
        
        if response.status_code == 200:
            spaces = response.json()
            space_count = len(spaces.get('results', []))
            print(f"✅ Connection successful! Found {space_count} spaces.")
            
            if space_count > 0:
                print("\n📁 Available spaces:")
                for space in spaces.get('results', [])[:5]:
                    print(f"  • {space.get('name')} ({space.get('key')})")
            
            return True
            
        elif response.status_code == 401:
            print("❌ Authentication failed. Check your email and API token.")
            return False
        elif response.status_code == 403:
            print("❌ Access denied. Check your permissions.")
            return False
        else:
            print(f"❌ Connection failed: HTTP {response.status_code}")
            print(f"Response: {response.text}")
            return False
            
    except Exception as e:
        print(f"❌ Connection test failed: {e}")
        return False


def test_confluence_publishing():
    """Test publishing a sample release note to Confluence."""
    print("\n🚀 Testing Confluence Publishing...")
    print("=" * 40)
    
    # Create a test release note
    test_version = f"v1.0.0-test-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
    test_content = f"""# Release Notes {test_version}

## 🎉 Test Release

This is a test release note generated by the Release Notes Generator.

### ✨ Features
- Test feature 1
- Test feature 2

### 🐛 Bug Fixes
- Fixed test issue 1
- Fixed test issue 2

### 📝 Notes
- Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
- This is a test publication

---
*Generated by Release Notes Generator*
"""
    
    # Save to temporary file
    test_file = Path(f'tmp_test_release_{test_version}.md')
    test_file.write_text(test_content, encoding='utf-8')
    
    print(f"📄 Created test file: {test_file}")
    print(f"📝 Version: {test_version}")
    
    try:
        # Test publishing
        print("\n📤 Publishing to Confluence...")
        result = publish(test_version, str(test_file))
        
        if result and 'id' in result:
            print("✅ Publishing successful!")
            print(f"📄 Page ID: {result.get('id')}")
            print(f"📝 Title: {result.get('title')}")
            
            if '_links' in result and 'webui' in result['_links']:
                print(f"🔗 URL: {result['_links']['webui']}")
            
            return True
        else:
            print("❌ Publishing failed - no page ID returned")
            return False
            
    except Exception as e:
        print(f"❌ Publishing failed: {e}")
        return False
    
    finally:
        # Clean up test file
        if test_file.exists():
            test_file.unlink()
            print(f"🧹 Cleaned up test file: {test_file}")


def test_confluence_api_endpoint():
    """Test the Confluence API endpoint in the server."""
    print("\n🌐 Testing Confluence API Endpoint...")
    print("=" * 40)
    
    try:
        response = requests.post('http://localhost:5000/api/confluence/test')
        
        if response.status_code == 200:
            data = response.json()
            print("✅ API endpoint working!")
            print(f"Status: {data.get('status')}")
            print(f"Message: {data.get('message')}")
            return True
        else:
            data = response.json() if response.headers.get('content-type', '').startswith('application/json') else {}
            print(f"❌ API endpoint failed: HTTP {response.status_code}")
            print(f"Error: {data.get('error', 'Unknown error')}")
            return False
            
    except requests.ConnectionError:
        print("❌ Could not connect to server. Make sure it's running:")
        print("python run_enhanced_server.py")
        return False
    except Exception as e:
        print(f"❌ API test failed: {e}")
        return False


def main():
    """Run all Confluence tests."""
    print("🧪 CONFLUENCE INTEGRATION TEST SUITE")
    print("=" * 50)
    
    tests_passed = 0
    total_tests = 3
    
    # Test 1: Connection
    if test_confluence_connection():
        tests_passed += 1
    
    # Test 2: API Endpoint
    if test_confluence_api_endpoint():
        tests_passed += 1
    
    # Test 3: Publishing (only if connection works)
    if tests_passed >= 1:
        if test_confluence_publishing():
            tests_passed += 1
    else:
        print("\n⚠️ Skipping publishing test due to connection failure")
    
    # Summary
    print(f"\n📊 TEST RESULTS: {tests_passed}/{total_tests} passed")
    
    if tests_passed == total_tests:
        print("🎉 All tests passed! Confluence integration is working perfectly.")
        print("\n✅ You can now:")
        print("1. Use the Confluence checkbox in the UI")
        print("2. Auto-publish release notes to Confluence")
        print("3. Share release notes with your team")
    else:
        print("⚠️ Some tests failed. Please check the configuration.")
        print("\n🔧 To fix:")
        print("1. Verify your .env file has correct Confluence settings")
        print("2. Check your API token is valid")
        print("3. Ensure you have Confluence permissions")
    
    return tests_passed == total_tests


if __name__ == '__main__':
    success = main()
    sys.exit(0 if success else 1)